const videos = [{
        id: 1,
        title: "Summer Championship — Finals",
        date: "Aug 15, 2025",
        duration: "12:45",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "VOD",
    },
    {
        id: 2,
        title: "Clutch Plays — Highlight Reel",
        date: "Jul 02, 2025",
        duration: "08:20",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "HIGHLIGHT",
    },
    ...[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72].map(id => ({
        id,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    })), {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }, {
        id: 3,
        title: "Pro Tips — 1v3 Retakes",
        date: "Jun 18, 2025",
        duration: "05:50",
        thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3cjF8yqeUhb0YcGr959-N3hfuGyTwIzwmSw&s",
        src: "https://www.w3schools.com/html/mov_bbb.mp4",
        tag: "GUIDE",
    }
];
export default videos;